### ISSUE TITLE
Rails 4.2 ActionController::Responder Integration

### ISSUE THREAD

**Issue by nwallace** [adamhunter/dossier#49]
Rails 4.2 removes `ActionController::Responder` into its own gem (refer [`responders` gem](https://github.com/plataformatec/responders) and [release notes](http://edgeguides.rubyonrails.org/4_2_release_notes.html#respond-with-class-level-respond-to)).

With Rails 4.2, Dossier gives the error `uninitialized constant ActionController::Responder`

A workaround is to include the new dependency in the client application *before* the dossier gem, e.g.:

    gem "responders"
    gem "dossier"

**Comment by caldwecr** [comment]
+1

**Comment by adamhunter** [comment]
Hey guys, thanks for the heads up and solution!  Fixed in https://github.com/adamhunter/dossier/pull/58 with a release due out later today.
