### ISSUE TITLE
How can I select a database column without displaying it as its own report column?

### ISSUE THREAD

**Issue by nathanl** [adamhunter/dossier#51]
Silly question, but if I knew how to do this once, I've forgotten.

Say I've got this query for a report:

```
SELECT name, color, id FROM widgets;
```

I don't want to display the id as its own column; instead, I want the `name` to link somewhere using that id.

```
def format_name(value, row)
  # build link using value and row[:id]
end
```

How can I prevent `id` from showing up as its own column?

**Comment by nathanl** [comment]
I suppose I could use https://github.com/adamhunter/dossier-display to give that column a class and style it as `display: none`, but that's awkward.

**Comment by nathanl** [comment]
Another solution is to `SELECT CONCAT(name, '--', id) AS name_link`, then format the header as just 'name' and format the values by splitting on the '--' and building a link. Also a bit awkward, but workable.

**Comment by adamhunter** [comment]
Still a pending feature request my friend :)
We usually just use a custom report template to hide columns at the moment.
